# AxisOS LightDM Default Configuration for Cinnamon Desktop
[Seat:*]
greeter-session=slick-greeter
greeter-hide-users=false
user-session=cinnamon
allow-guest=false
session-wrapper=/etc/X11/Xsession
xserver-command=X -core -noreset -background none
