# AxisOS Package Manager Configuration
# /etc/axis/axis.conf

# Local system package cache and index
repo file:///var/lib/axis/repo-index.json
repo file:///etc/axis/repo-index.json

# Upstream GitHub Repository (Free, zero-cost CDN hosted on GitHub)
repo https://raw.githubusercontent.com/jackyphuti/AxisOS/main/pkg-mgr/examples
